### ISSUE TITLE
add jQuery Sparkle XSS to Gadgets table

### ISSUE THREAD

**Issue by CmdEngineer** [BlackFan/client-side-prototype-pollution#16]
In the jquery sparkles page [we can see there's an obvious XSS](https://github.com/BlackFan/client-side-prototype-pollution/blob/master/pp/jquery-sparkle.md) but it's not documented in the gadgets table

**Comment by shhnjk** [comment]
The page does mention that `The parsing is poorly written and also has XSS`.
